version: "3.8"

services:
  backend:
    container_name: cpp-backend
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    env_file:
      - backend/.env
    command: flask run --host=0.0.0.0 --port=5000
    restart: unless-stopped

  frontend:
    container_name: cpp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # 👈 local-only Dockerfile
    ports:
        - "3000:3000"
    volumes:
        - ./frontend:/app
        - /app/node_modules
    env_file:
        - ./frontend/.env
    environment:
        - VITE_API_BASE=http://backend:5003
    depends_on:
        - backend
    restart: unless-stopped

