services:
  backend:
    container_name: cpp-backend
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    container_name: cpp-frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
