services:
  backend:
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Enables debugger and auto-reload


