version: "3.8"

services:
  backend:
    container_name: cpp-backend
    build: ./backend
    ports:
      - "5003:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    container_name: cpp-frontend
    build:
      context: ./frontend
      target: builder  # build dev mode
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:5003
    command: npm run dev
    depends_on:
      - backend
    restart: unless-stopped
